# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWind.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWind(object):
    def __init__(self, MainWind):
        self.timer_camera = QtCore.QTimer()  # 定时器
        self.setupUi(MainWind)
        self.slot_init(MainWind)  # 设置槽函数

    def slot_init(self, MainWind):
        self.openCamera.clicked.connect(MainWind.openCamera)
        self.takePhoto.clicked.connect(MainWind.takePhoto)
        self.closeCamera.clicked.connect(MainWind.closeCamera)
        self.Exit.clicked.connect(MainWind.close)
        self.timer_camera.timeout.connect(MainWind.showCamera)

    def setupUi(self, MainWind):
        MainWind.setObjectName("MainWind")
        MainWind.resize(634, 518)
        self.gridLayout = QtWidgets.QGridLayout(MainWind)
        self.gridLayout.setObjectName("gridLayout")
        self.closeCamera = QtWidgets.QPushButton(MainWind)
        self.closeCamera.setObjectName("closeCamera")
        self.gridLayout.addWidget(self.closeCamera, 5, 3, 1, 1, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom)
        self.openCamera = QtWidgets.QPushButton(MainWind)
        self.openCamera.setMinimumSize(QtCore.QSize(92, 0))
        self.openCamera.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.openCamera.setObjectName("openCamera")
        self.gridLayout.addWidget(self.openCamera, 5, 0, 1, 1, QtCore.Qt.AlignLeft | QtCore.Qt.AlignBottom)
        self.Exit = QtWidgets.QPushButton(MainWind)
        self.Exit.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Exit.setObjectName("Exit")
        self.gridLayout.addWidget(self.Exit, 0, 1, 1, 2)
        self.takePhoto = QtWidgets.QPushButton(MainWind)
        self.takePhoto.setObjectName("takePhoto")
        self.gridLayout.addWidget(self.takePhoto, 5, 1, 1, 2)
        self.showCamerLabel = QtWidgets.QLabel(MainWind)  # 用于实时输出摄像头画面
        self.showCamerLabel.setText("")
        self.showCamerLabel.setObjectName("showCamerLabel")
        self.gridLayout.addWidget(self.showCamerLabel, 1, 0, 1, 4)
        self.retranslateUi(MainWind)
        QtCore.QMetaObject.connectSlotsByName(MainWind)

    def retranslateUi(self, MainWind):
        _translate = QtCore.QCoreApplication.translate
        MainWind.setWindowTitle(_translate("MainWind", "Dialog"))
        self.closeCamera.setText(_translate("MainWind", "closeCamera"))
        self.openCamera.setText(_translate("MainWind", "OpenCamera"))
        self.Exit.setText(_translate("MainWind", "Exit"))
        self.takePhoto.setText(_translate("MainWind", "takePhoto"))
