# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWind.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWind(object):
    def __init__(self, MainWind):
        self.timer_camera = QtCore.QTimer()  # 定时器
        self.setupUi(MainWind)
        self.slot_init(MainWind)  # 设置槽函数

    def slot_init(self, MainWind):
        self.openCamera.clicked.connect(MainWind.openCamera)
        self.takePhoto.clicked.connect(MainWind.takePhoto)
        self.closeCamera.clicked.connect(MainWind.closeCamera)
        self.train.clicked.connect(MainWind.train)
        self.nameInput.returnPressed.connect(MainWind.nameInput)  # 获取输入的名字
        self.batchTest.clicked.connect(MainWind.batchTest)
        self.timer_camera.timeout.connect(MainWind.showCamera)  # 定时器

    def setupUi(self, MainWind):
        MainWind.setObjectName("MainWind")
        MainWind.resize(634, 518)
        self.gridLayout = QtWidgets.QGridLayout(MainWind)
        self.gridLayout.setObjectName("gridLayout")
        self.openCamera = QtWidgets.QPushButton(MainWind)
        self.openCamera.setMinimumSize(QtCore.QSize(92, 0))
        self.openCamera.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.openCamera.setObjectName("openCamera")
        self.gridLayout.addWidget(self.openCamera, 6, 0, 1, 1, QtCore.Qt.AlignLeft | QtCore.Qt.AlignBottom)
        self.train = QtWidgets.QPushButton(MainWind)
        self.train.setObjectName("train")
        self.gridLayout.addWidget(self.train, 0, 3, 1, 1)
        self.closeCamera = QtWidgets.QPushButton(MainWind)
        self.closeCamera.setObjectName("closeCamera")
        self.gridLayout.addWidget(self.closeCamera, 6, 3, 1, 1, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom)
        self.nameInput = QtWidgets.QLineEdit(MainWind)
        self.nameInput.setObjectName("nameInput")
        self.nameInput.setPlaceholderText("请输入姓名")
        self.gridLayout.addWidget(self.nameInput, 0, 2, 1, 1)
        self.takePhoto = QtWidgets.QPushButton(MainWind)
        self.takePhoto.setObjectName("takePhoto")
        self.gridLayout.addWidget(self.takePhoto, 0, 0, 1, 1)
        self.showCamerLabel = QtWidgets.QLabel(MainWind)
        self.showCamerLabel.setText("")
        self.showCamerLabel.setObjectName("showCamerLabel")
        self.showCamerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.showCamerLabel, 2, 0, 4, 4)
        self.batchTest = QtWidgets.QPushButton(MainWind)
        self.batchTest.setObjectName("batchTest")
        self.gridLayout.addWidget(self.batchTest, 6, 2, 1, 1)
        self.retranslateUi(MainWind)
        QtCore.QMetaObject.connectSlotsByName(MainWind)

    def retranslateUi(self, MainWind):
        _translate = QtCore.QCoreApplication.translate
        MainWind.setWindowTitle(_translate("MainWind", "Dialog"))
        self.openCamera.setText(_translate("MainWind", "打开摄像头"))
        self.train.setText(_translate("MainWind", "开始训练"))
        self.closeCamera.setText(_translate("MainWind", "关闭摄像头"))
        self.nameInput.setText(_translate("MainWind", ""))
        self.takePhoto.setText(_translate("MainWind", "人脸录入"))
        self.batchTest.setText(_translate("MainWind", "批量测试"))
